Update script path comment in omitViewSegments.js
the current path throws error. found the script under /scripts.

meghana.mr@dev-meghana:/opt/countly/plugins/views$ sudo node omitViewSeg.js
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module './../../../plugins/pluginManager.js'
Require stack:
- /opt/countly/plugins/views/omitViewSeg.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/opt/countly/plugins/views/omitViewSeg.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/countly/plugins/views/omitViewSeg.js' ]
}